### PR TITLE
Javascript Weather app 

### PR DESCRIPTION
**Pull request by barackm**
### Well, In this project I have implemented the following:

- [ ] Configure webpack
- [ ] Create modules
- [ ] Work with modules
- [ ] Fetch data from the internet using fetch in JavaScript
- [ ] Create HTML elements using JavaScipt
- [ ] Use modern JavaScript ES6
- [ ] Deploy the website to heroku

### CODE REVIEW

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [ ] Git flow is used properly.
- [ ] README includes instructions on how to run the project locally.
## To Improve 🙏
- [ ] App should have a toggle functionality between Celsius, and Fahrenheit. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png).
# Optional
- [ ] App may fetch the current geolocation of the user when it is first accessed and fetches the weather from that location
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Comment by barackm** [comment]
Hi @sajjad, I have implemented that functionality, when you click on 'C'(celsius) it converts the degrees in Faraneiht.

**Review by GzimAsani — APPROVED** [review]
# STATUS: Project Accepted :green_circle: 

## Hello @barackm. You've done a great job with your project I absolutely love the layout that you have given to your page :clap:. Good luck with your next projects :+1: 

# HAPPY CODING :computer: :desktop_computer:

**Comment by barackm** [comment]
Thank you!!

**Pull request merged**
